### ISSUE TITLE
依赖安装问题

### ISSUE THREAD

**Issue by Geniucker** [cyc-987/EE-Archive#1]
应该把py依赖写在requirements.txt里，action里pip install -r requirements.txt
因为有些插件是要装py模块的，比如说mkdocs不支持删除线语法，要支持就要装一个插件，到时候你只要加到requirements.txt就行
最近刚好在弄mkdocs material\doge
https://github.com/ZJUIntl-share/zjuintl-icicles

**Comment by cyc-987** [comment]
所以它部署的时候是怎么找到requirements.txt的

**Comment by Geniucker** [comment]
放项目根目录
然后把action里面的
```shell
pip install \
          mkdocs-material \
          mkdocs-git-revision-date-localized-plugin \
          mkdocs-git-committers-plugin-2
```
改成 pip install -r requirements.txt
因为在checkout之后当前路径就是项目根目录

**Comment by cyc-987** [comment]
有这种事，我悟了
